from frontend.models import AuditLog


def log_action(user, action, module, affected_id=None, status='success', details=None, request=None):
    """Creates one AuditLog row; the only path allowed to create them."""
    ip = None
    if request:
        x_forwarded = request.META.get('HTTP_X_FORWARDED_FOR')
        ip = x_forwarded.split(',')[0] if x_forwarded else request.META.get('REMOTE_ADDR')

    return AuditLog.objects.create(
        user=user,
        action=action,
        module=module,
        affected_id=affected_id,
        status=status,
        details=details or {},
        ip_address=ip,
    )


LOGIN_SUCCESS = 'LOGIN_SUCCESS'
LOGIN_FAILED = 'LOGIN_FAILED'
LOGOUT = 'LOGOUT'
PROFILE_UPDATED = 'PROFILE_UPDATED'
PASSWORD_CHANGED = 'PASSWORD_CHANGED'
ACCOUNT_LOCKED = 'ACCOUNT_LOCKED'
# Rule: unused -- resets log under PASSWORD_CHANGED instead.
PASSWORD_RESET_REQUESTED = 'PASSWORD_RESET_REQUESTED'
PASSWORD_RESET_COMPLETED = 'PASSWORD_RESET_COMPLETED'

USER_CREATED = 'USER_CREATED'
# Assumption: unreachable -- no view edits a user's fields after creation.
USER_UPDATED = 'USER_UPDATED'
USER_DEACTIVATED = 'USER_DEACTIVATED'
USER_REACTIVATED = 'USER_REACTIVATED'
# Assumption: unreachable -- no view changes a user's role after creation.
USER_ROLE_CHANGED = 'USER_ROLE_CHANGED'
USER_DELETED = 'USER_DELETED'
USER_CREDENTIALS_RESENT = 'USER_CREDENTIALS_RESENT'

PRODUCT_CREATED = 'PRODUCT_CREATED'
PRODUCT_UPDATED = 'PRODUCT_UPDATED'
PRODUCT_DEACTIVATED = 'PRODUCT_DEACTIVATED'
PRODUCT_REACTIVATED = 'PRODUCT_REACTIVATED'
PRODUCT_DELETED = 'PRODUCT_DELETED'
CATEGORY_CREATED = 'CATEGORY_CREATED'
CATEGORY_UPDATED = 'CATEGORY_UPDATED'
CATEGORY_DEACTIVATED = 'CATEGORY_DEACTIVATED'
CATEGORY_REACTIVATED = 'CATEGORY_REACTIVATED'
CATEGORY_DELETED = 'CATEGORY_DELETED'

SUPPLIER_CREATED = 'SUPPLIER_CREATED'
SUPPLIER_UPDATED = 'SUPPLIER_UPDATED'
SUPPLIER_DEACTIVATED = 'SUPPLIER_DEACTIVATED'
SUPPLIER_REACTIVATED = 'SUPPLIER_REACTIVATED'
SUPPLIER_DELETED = 'SUPPLIER_DELETED'

PO_CREATED = 'PO_CREATED'
PO_SUBMITTED = 'PO_SUBMITTED'
PO_APPROVED = 'PO_APPROVED'
PO_REJECTED = 'PO_REJECTED'
PO_RECEIVED = 'PO_RECEIVED'
PO_CANCELLED = 'PO_CANCELLED'

SALE_CREATED = 'SALE_CREATED'
SALE_SUBMITTED = 'SALE_SUBMITTED'
SALE_APPROVED = 'SALE_APPROVED'
SALE_REJECTED = 'SALE_REJECTED'
SALE_CANCELLED = 'SALE_CANCELLED'
SALE_INVOICE_PRINTED = 'SALE_INVOICE_PRINTED'

INVENTORY_VIEWED = 'INVENTORY_VIEWED'
LOW_STOCK_ALERT_SENT = 'LOW_STOCK_ALERT_SENT'
OUT_OF_STOCK_ALERT_SENT = 'OUT_OF_STOCK_ALERT_SENT'
# Rule: unused -- counts log under ADJUSTMENT_REQUESTED/APPROVED instead.
PHYSICAL_COUNT_PERFORMED = 'PHYSICAL_COUNT_PERFORMED'

ADJUSTMENT_REQUESTED = 'ADJUSTMENT_REQUESTED'
ADJUSTMENT_APPROVED = 'ADJUSTMENT_APPROVED'
ADJUSTMENT_REJECTED = 'ADJUSTMENT_REJECTED'
# Rule: distinct from ADJUSTMENT_APPROVED -- no human approved this.
ADJUSTMENT_AUTO_POSTED = 'ADJUSTMENT_AUTO_POSTED'
# Rule: fires when the cumulative cap deflects an AUTO match.
ADJUSTMENT_AUTO_DEFLECTED = 'ADJUSTMENT_AUTO_DEFLECTED'

APPROVAL_POLICY_CREATED = 'APPROVAL_POLICY_CREATED'
APPROVAL_POLICY_UPDATED = 'APPROVAL_POLICY_UPDATED'
APPROVAL_POLICY_DEACTIVATED = 'APPROVAL_POLICY_DEACTIVATED'
APPROVAL_POLICY_REACTIVATED = 'APPROVAL_POLICY_REACTIVATED'

REPORT_GENERATED = 'REPORT_GENERATED'
REPORT_EXPORTED_PDF = 'REPORT_EXPORTED_PDF'
REPORT_EXPORTED_CSV = 'REPORT_EXPORTED_CSV'

AI_MODEL_RETRAINED = 'AI_MODEL_RETRAINED'
AI_MODEL_RETRAIN_FAILED = 'AI_MODEL_RETRAIN_FAILED'
AI_FORECASTS_GENERATED = 'AI_FORECASTS_GENERATED'
# Rule: separate from SETTINGS_UPDATED -- these fields redefine SLOW/DEAD.
AI_CLASSIFIER_WEIGHTS_CHANGED = 'AI_CLASSIFIER_WEIGHTS_CHANGED'
AI_CLASSIFICATION_RUN = 'AI_CLASSIFICATION_RUN'
AI_CLASSIFICATION_FAILED = 'AI_CLASSIFICATION_FAILED'
AI_PRODUCT_RECLASSIFIED = 'AI_PRODUCT_RECLASSIFIED'
# Rule: no forecast-specific export action -- REPORT_EXPORTED_* covers it.
AI_ACTUAL_DEMAND_BACKFILLED = 'AI_ACTUAL_DEMAND_BACKFILLED'

SETTINGS_UPDATED = 'SETTINGS_UPDATED'
