from decimal import Decimal, InvalidOperation
import json

from django import forms
from django.utils import timezone

from frontend.models import (
    ApprovalPolicy,
    Category,
    InventoryAdjustment,
    Product,
    PurchaseOrder,
    SaleTransaction,
    Supplier,
    SystemSettings,
    UnitOfMeasurement,
    User,
)

# Rule: status is a form-only field, consumed by the view to set is_active.
STATUS_CHOICES = [("Active", "Active"), ("Inactive", "Inactive")]


class ProductForm(forms.ModelForm):

    class Meta:
        model = Product
        fields = [
            "name", "sku", "barcode", "category", "supplier", "brand",
            "unit", "purchase_price", "selling_price", "tax_rate", "reorder_level",
        ]

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        # Rule: sku auto-generates if left blank -- see clean_sku().
        self.fields["sku"].required = False
        self.fields["barcode"].required = False
        self.fields["unit"].required = False
        self.fields["reorder_level"].required = False
        # Security: category/supplier queryset restricted to active, not just the UI.
        self.fields["category"].queryset = Category.objects.filter(is_active=True)
        self.fields["supplier"].queryset = Supplier.objects.filter(is_active=True)

    def clean_sku(self):
        sku = (self.cleaned_data.get("sku") or "").strip()
        if sku:
            return sku
        # Rule: flags this instance so Product.save() retries only on a real collision.
        self.instance._sku_autogenerated = True
        return self.instance._generate_sku()

    def clean_barcode(self):
        barcode = (self.cleaned_data.get("barcode") or "").strip()
        return barcode or None

    def clean_unit(self):
        return self.cleaned_data.get("unit") or UnitOfMeasurement.PIECE

    def clean_reorder_level(self):
        # Rule: blank falls back to the admin-configured default, not the model's own.
        value = self.cleaned_data.get("reorder_level")
        return value if value is not None else SystemSettings.get_settings().default_reorder_level

    def clean_purchase_price(self):
        value = self.cleaned_data.get("purchase_price")
        if value is not None and value < 0:
            raise forms.ValidationError("Purchase price cannot be negative.")
        return value

    def clean_selling_price(self):
        value = self.cleaned_data.get("selling_price")
        if value is not None and value < 0:
            raise forms.ValidationError("Selling price cannot be negative.")
        return value

    def clean_tax_rate(self):
        # Assumption: required, so value is never None here -- no blank-to-0 fallback.
        value = self.cleaned_data.get("tax_rate")
        if value < 0:
            raise forms.ValidationError("Tax rate cannot be negative.")
        return value

class CategoryForm(forms.ModelForm):
    status = forms.ChoiceField(choices=STATUS_CHOICES, required=False, initial="Active")

    class Meta:
        model = Category
        fields = ["name", "description"]


class SupplierForm(forms.ModelForm):
    status = forms.ChoiceField(choices=STATUS_CHOICES, required=False, initial="Active")

    class Meta:
        model = Supplier
        fields = ["supplier_name", "company_name", "contact_person", "email", "phone", "address"]


def parse_line_items(raw_json, min_quantity=1):
    """Returns (items, errors); items carry real Product instances."""
    # Assumption: productLabel is a product pk string, not a display name.
    try:
        raw_items = json.loads(raw_json or "[]")
    except (ValueError, TypeError):
        return [], ["Line items could not be read. Please try again."]

    if not isinstance(raw_items, list) or not raw_items:
        return [], ["At least one line item is required."]

    errors = []
    parsed = []
    for index, raw in enumerate(raw_items, start=1):
        if not isinstance(raw, dict):
            errors.append(f"Line {index}: malformed line item.")
            continue

        try:
            product = Product.objects.get(pk=raw.get("productLabel"), is_active=True)
        except (Product.DoesNotExist, ValueError, TypeError):
            errors.append(f"Line {index}: product is invalid or no longer active.")
            continue

        try:
            quantity = int(raw.get("quantity"))
        except (TypeError, ValueError):
            quantity = None
        if quantity is None or quantity < min_quantity:
            errors.append(f"Line {index}: quantity must be at least {min_quantity}.")
            continue

        try:
            unit_price = Decimal(str(raw.get("unitPrice")))
        except (InvalidOperation, TypeError, ValueError):
            unit_price = None
        if unit_price is None or unit_price < 0:
            errors.append(f"Line {index}: unit price cannot be negative.")
            continue

        try:
            discount = Decimal(str(raw.get("discount") or 0))
        except InvalidOperation:
            errors.append(f"Line {index}: discount must be numeric.")
            continue
        if discount < 0:
            errors.append(f"Line {index}: discount cannot be negative.")
            continue

        # Rule: tax always comes from Product.tax_rate -- never the client.
        tax = product.tax_rate

        parsed.append({
            "product": product, "quantity": quantity,
            "unit_price": unit_price, "discount": discount, "tax": tax,
        })

    return parsed, errors


class PurchaseOrderForm(forms.ModelForm):
    """Header fields only -- line items arrive separately as items_json."""

    class Meta:
        model = PurchaseOrder
        fields = ["supplier", "expected_delivery", "notes"]

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields["expected_delivery"].required = False
        self.fields["notes"].required = False
        # Security: supplier queryset restricted to active.
        self.fields["supplier"].queryset = Supplier.objects.filter(is_active=True)

    def clean_expected_delivery(self):
        # Rule: order_date is always today, so this is one real-world check.
        expected_delivery = self.cleaned_data.get("expected_delivery")
        if expected_delivery and expected_delivery < timezone.localdate():
            raise forms.ValidationError("Expected delivery date cannot be in the past.")
        return expected_delivery


class SaleTransactionForm(forms.ModelForm):

    class Meta:
        model = SaleTransaction
        fields = ["customer_name", "notes"]

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields["customer_name"].required = False
        self.fields["notes"].required = False


class AdjustmentForm(forms.ModelForm):
    """Rule: product queryset is NOT restricted to is_active -- correcting a
    stale count on a deactivated product is legitimate."""

    class Meta:
        model = InventoryAdjustment
        fields = ["product", "adjustment_type", "quantity", "reason_code", "reason"]

    def clean_quantity(self):
        # Rule: 0 is technically valid but a no-op -- rejected as meaningless.
        value = self.cleaned_data.get("quantity")
        if value is not None and value <= 0:
            raise forms.ValidationError("Quantity must be greater than zero.")
        return value


class UserForm(forms.ModelForm):
    """No password field -- UserListCreateView.post() generates and emails one."""

    class Meta:
        model = User
        fields = ["full_name", "username", "employee_id", "email", "role"]


class SystemSettingsForm(forms.ModelForm):
    """Notification-toggle fields aren't bound here -- only via /admin/."""

    class Meta:
        model = SystemSettings
        fields = [
            "company_name", "company_logo", "company_address", "company_email", "company_phone",
            "company_tax_number", "company_website",
            "default_reorder_level", "forecast_period_weeks", "forecast_retrain_days",
            "slow_moving_threshold_days", "dead_stock_threshold_days", "session_timeout_seconds",
            "weight_recency", "weight_turnover", "weight_coverage", "weight_frequency",
            "slow_index_threshold", "dead_index_threshold", "target_days_of_cover",
            "min_observation_days", "min_sale_events", "extreme_coverage_days",
        ]

    # Rule: blank falls back to the row's own current value -- always an update.
    _FALLBACK_TO_INSTANCE_FIELDS = [
        "company_name", "default_reorder_level", "forecast_period_weeks",
        "forecast_retrain_days", "slow_moving_threshold_days",
        "dead_stock_threshold_days", "session_timeout_seconds",
        "weight_recency", "weight_turnover", "weight_coverage", "weight_frequency",
        "slow_index_threshold", "dead_index_threshold", "target_days_of_cover",
        "min_observation_days", "min_sale_events", "extreme_coverage_days",
    ]

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for name in self.fields:
            self.fields[name].required = False

    def clean(self):
        cleaned = super().clean()
        for name in self._FALLBACK_TO_INSTANCE_FIELDS:
            # Assumption: `is None`, not falsy -- 0.00 is a legitimate weight.
            if cleaned.get(name) is None:
                cleaned[name] = getattr(self.instance, name)
        return cleaned


class ReasonForm(forms.Form):
    """Shared by every reject()/cancel() action requiring a non-empty reason."""
    reason = forms.CharField(widget=forms.Textarea, min_length=1, error_messages={
        "required": "A reason is required.",
        "min_length": "A reason is required.",
    })


class ApprovalPolicyForm(forms.ModelForm):
    """reason_code is a plain CharField -- blank means "matches anything"."""

    class Meta:
        model = ApprovalPolicy
        fields = [
            "name", "transaction_type", "reason_code",
            "min_value", "max_value", "max_variance_pct",
            "required_level", "block_self_approval", "priority", "notes",
            "cumulative_window_days", "cumulative_value_cap",
        ]

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for name in (
            "reason_code", "max_value", "max_variance_pct",
            "cumulative_window_days", "cumulative_value_cap", "notes",
        ):
            self.fields[name].required = False

    def clean_priority(self):
        value = self.cleaned_data.get("priority")
        if value is not None and value < 1:
            raise forms.ValidationError("Priority must be a positive number.")
        return value

    def clean(self):
        cleaned = super().clean()
        min_value = cleaned.get("min_value")
        max_value = cleaned.get("max_value")
        if min_value is not None and max_value is not None and max_value < min_value:
            raise forms.ValidationError("Max value can't be less than min value.")
        # Rule: window and cap must both be set or both blank -- one alone is a no-op.
        window = cleaned.get("cumulative_window_days")
        cap = cleaned.get("cumulative_value_cap")
        if bool(window) != (cap is not None):
            self.add_error("cumulative_value_cap", "Set both cumulative window and cap, or leave both blank.")
        return cleaned

    def clean_reason_code(self):
        value = self.cleaned_data.get("reason_code") or ""
        return value.strip()
