# Generated by Django 6.0.7 on 2026-08-13 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0002_product_tax_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorder',
            name='order_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='saletransaction',
            name='transaction_date',
            field=models.DateField(),
        ),
    ]
