# Generated by Django 6.0.7 on 2026-08-14 08:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0003_alter_purchaseorder_order_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='saletransaction',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='saletransaction',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sales_approved', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='saletransaction',
            name='rejected_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('low_stock', 'Low Stock Alert'), ('out_of_stock', 'Out of Stock'), ('po_pending', 'Purchase Order Pending Approval'), ('po_approved', 'Purchase Order Approved'), ('po_rejected', 'Purchase Order Rejected'), ('adj_pending', 'Adjustment Pending Approval'), ('adj_approved', 'Adjustment Approved'), ('ai_replenish', 'AI Replenishment Recommendation'), ('ai_slow', 'AI Slow-Moving Stock Alert'), ('ai_dead', 'AI Dead Stock Alert'), ('password_changed', 'Password Changed'), ('sale_completed', 'Sale Completed'), ('sale_pending', 'Sale Pending Approval')], max_length=30),
        ),
        migrations.AlterField(
            model_name='saletransaction',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending Approval'), ('completed', 'Completed'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], default='draft', max_length=20),
        ),
    ]
