# Generated by Django 6.0.7 on 2026-08-23 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0005_purchaseorder_cancelled_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryadjustment',
            name='reason_code',
            field=models.CharField(choices=[('damage', 'Damaged / Broken'), ('expiry', 'Expired / Obsolete'), ('count_correction', 'Physical Count Correction'), ('receiving_error', 'Receiving Error Correction'), ('shrinkage_unknown', 'Unexplained Loss / Shrinkage'), ('other', 'Other')], default='other', max_length=20),
        ),
        migrations.AddField(
            model_name='inventoryclassification',
            name='abc_class',
            field=models.CharField(choices=[('A', 'A — Top revenue contributors'), ('B', 'B — Mid revenue contributors'), ('C', 'C — Low / no revenue contribution')], default='C', max_length=1),
        ),
        migrations.CreateModel(
            name='ApprovalPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120)),
                ('transaction_type', models.CharField(choices=[('purchase_order', 'Purchase Order'), ('adjustment', 'Inventory Adjustment'), ('sale_cancel', 'Sale Cancellation')], max_length=30)),
                ('reason_code', models.CharField(blank=True, max_length=40)),
                ('abc_class', models.CharField(blank=True, max_length=1)),
                ('min_value', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('max_value', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('max_variance_pct', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('required_level', models.CharField(choices=[('auto', 'Auto-approve (no human approval)'), ('supervisor', 'Supervisor or Admin'), ('admin', 'Admin only')], max_length=20)),
                ('block_self_approval', models.BooleanField(default=True)),
                ('priority', models.PositiveSmallIntegerField(db_index=True)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'approval_policies',
                'ordering': ['transaction_type', 'priority'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('transaction_type', 'priority'), name='uniq_active_policy_priority_per_type')],
            },
        ),
    ]
