# Generated by Django 6.0.7 on 2026-08-23 05:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0007_seed_approval_policies'),
    ]

    operations = [
        migrations.AddField(
            model_name='approvalpolicy',
            name='cumulative_value_cap',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name='approvalpolicy',
            name='cumulative_window_days',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inventoryadjustment',
            name='resolved_policy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_adjustments', to='frontend.approvalpolicy'),
        ),
        migrations.AddField(
            model_name='inventoryadjustment',
            name='was_auto_posted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='abc_last_recomputed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='inventoryclassification',
            name='abc_class',
            field=models.CharField(blank=True, choices=[('A', 'A — Top revenue contributors'), ('B', 'B — Mid revenue contributors'), ('C', 'C — Low / no revenue contribution')], default='', max_length=1),
        ),
    ]
