# Generated by Django 6.0.7 on 2026-08-23 08:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0010_remove_abc_class_policy_row'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='approvalpolicy',
            name='abc_class',
        ),
    ]
