# Generated by Django 6.0.7 on 2026-08-23 11:56

import frontend.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0011_remove_approvalpolicy_abc_class'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsettings',
            name='company_tax_number',
            field=models.CharField(blank=True, max_length=50, verbose_name='Tax / BIN number'),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='company_website',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='systemsettings',
            name='company_logo',
            field=models.FileField(blank=True, null=True, upload_to='company/', validators=[frontend.validators.validate_company_logo]),
        ),
    ]
