# Generated by Django 6.0.7 on 2026-08-24 09:37

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0012_systemsettings_company_tax_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventoryclassification',
            name='abc_class',
        ),
        migrations.RemoveField(
            model_name='systemsettings',
            name='abc_last_recomputed_at',
        ),
        migrations.AddField(
            model_name='inventoryclassification',
            name='confidence',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='inventoryclassification',
            name='coverage_score',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='inventoryclassification',
            name='frequency_score',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='inventoryclassification',
            name='recency_score',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='inventoryclassification',
            name='stagnation_index',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inventoryclassification',
            name='turnover_score',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='dead_index_threshold',
            field=models.PositiveSmallIntegerField(default=70),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='min_observation_days',
            field=models.PositiveIntegerField(default=30),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='min_sale_events',
            field=models.PositiveIntegerField(default=2),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='slow_index_threshold',
            field=models.PositiveSmallIntegerField(default=40),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='target_days_of_cover',
            field=models.PositiveIntegerField(default=90),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='weight_coverage',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.20'), max_digits=3),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='weight_frequency',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.10'), max_digits=3),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='weight_recency',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.40'), max_digits=3),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='weight_turnover',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.30'), max_digits=3),
        ),
        migrations.AlterField(
            model_name='inventoryclassification',
            name='classification',
            field=models.CharField(choices=[('fast', 'Fast-Moving'), ('slow', 'Slow-Moving'), ('dead', 'Dead Stock'), ('insufficient_data', 'Insufficient Data')], max_length=20),
        ),
        migrations.AlterField(
            model_name='inventoryclassification',
            name='days_since_last_sale',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
