# Generated by Django 6.0.7 on 2026-08-24 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0013_stagnation_index_and_abc_removal'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryclassification',
            name='flagged_by_rule',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='extreme_coverage_days',
            field=models.PositiveIntegerField(default=730),
        ),
    ]
