"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.16.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
import sys
from pathlib import Path
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

load_dotenv(BASE_DIR / '.env')

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ['DJANGO_SECRET_KEY']

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get('DJANGO_DEBUG', 'False') == 'True'

ALLOWED_HOSTS = os.environ.get('DJANGO_ALLOWED_HOSTS', '').split(',') if os.environ.get('DJANGO_ALLOWED_HOSTS') else []


# Application definition

INSTALLED_APPS = [
    'frontend',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    # Phase 8.99 — DEPLOYMENT.md's documented placement ("must be second").
    # Serves STATIC_ROOT directly from the WSGI process — no separate CDN/
    # nginx static tier needed on Render. Also active under DEBUG=True
    # (harmless — Django's own static-file dev serving still runs first
    # via urls.py's staticfiles_urlpatterns) so `collectstatic` + a local
    # DEBUG=False run can be verified before ever touching Render.
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / "frontend" / "templates"],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases
# PostgreSQL (Phase 3.8 — TECH_STACK.md's documented engine, replacing the
# SQLite dev default). Credentials come from .env, never hardcoded here.

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.environ['DB_NAME'],
        'USER': os.environ['DB_USER'],
        'PASSWORD': os.environ['DB_PASSWORD'],
        'HOST': os.environ.get('DB_HOST', 'localhost'),
        'PORT': os.environ.get('DB_PORT', '5432'),
        # Phase 8.99 — 'prefer' is psycopg's own default when unset, so
        # this is a no-op locally; lets DB_SSLMODE=require be set in
        # Render if the managed Postgres connection needs it enforced
        # (Render's external DB URLs generally do; internal/same-region
        # connections generally don't) without a code change either way.
        'OPTIONS': {'sslmode': os.environ.get('DB_SSLMODE', 'prefer')},
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
        'OPTIONS': {'min_length': 8},
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
    # Phase 4 — SECURITY.md's StrongPasswordValidator (uppercase, lowercase,
    # digit, special char), stacked on top of the 4 built-in validators above.
    {
        'NAME': 'frontend.validators.StrongPasswordValidator',
    },
]

# Password hashing (Phase 4) — SECURITY.md item 1 / 01_AUTH.md's "Password
# hashing: Argon2" business rule. Argon2 first so it's used for every new/
# changed password; the rest stay listed so Django can still verify (and
# transparently upgrade) any password hashed with them previously.
PASSWORD_HASHERS = [
    'django.contrib.auth.hashers.Argon2PasswordHasher',
    'django.contrib.auth.hashers.PBKDF2PasswordHasher',
    'django.contrib.auth.hashers.PBKDF2SHA1PasswordHasher',
    'django.contrib.auth.hashers.BCryptSHA256PasswordHasher',
]

# Custom user model (Phase 3.7) — SCHEMA.md §1 User. Must be set before the
# first migration; every FK in frontend/models.py already targets
# settings.AUTH_USER_MODEL in anticipation of this.
AUTH_USER_MODEL = 'frontend.User'

# Real login lives at frontend:login, not Django's default /accounts/login/
# (project_memory.md §12 bug #1) — this is what @login_required and
# LoginRequiredMixin (and frontend/mixins.py's RoleRequiredMixin, which
# extends it) redirect unauthenticated users to.
LOGIN_URL = 'frontend:login'

# Account lockout (Phase 4) — 01_AUTH.md's business rules table describes
# these as "configurable," but SCHEMA.md's SystemSettings model has no
# matching fields; only ENVIRONMENT.md documents them, as env vars. Used
# as specified there rather than adding SystemSettings fields to work
# around the gap — see docs/project_memory.md for the full note.
MAX_LOGIN_ATTEMPTS = int(os.environ.get('MAX_LOGIN_ATTEMPTS', '5'))
LOCKOUT_DURATION = int(os.environ.get('LOCKOUT_DURATION', '300'))

# Session/CSRF cookie hardening (Phase 4) — 01_AUTH.md: "Session cookie:
# HttpOnly + Secure + SameSite=Lax". *_SECURE is tied to DEBUG rather than
# hardcoded True, since a Secure cookie is never sent back over plain HTTP
# local dev — this project has no separate dev/production settings module
# (see docs/project_memory.md §13) to split it into instead.
SESSION_COOKIE_HTTPONLY = True
SESSION_COOKIE_SAMESITE = 'Lax'
SESSION_COOKIE_SECURE = not DEBUG
CSRF_COOKIE_SECURE = not DEBUG


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

# Phase 8.6 (BUG-37) — the business operates in Bangladesh; every rendered
# timestamp (AuditLog especially — a compliance record) should read in
# local Bangladesh time, not UTC. USE_TZ stays True: everything is still
# stored in the database as real UTC instants (Postgres `timestamptz`) —
# only the *display* conversion changes. Django performs this conversion
# automatically wherever a value passes through `{{ value|date:... }}` or
# `timezone.localtime()`, so no per-view changes were needed beyond the
# dashboard greeting (frontend/views.py), which now also reads
# `timezone.localtime()` for consistency.
TIME_ZONE = 'Asia/Dhaka'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Phase 8.99 — collectstatic's target directory, gathered from
# frontend/static/ via AppDirectoriesFinder (frontend is in INSTALLED_APPS;
# no STATICFILES_DIRS needed, nothing else is a static source). Required
# for both `manage.py collectstatic` (DEPLOYMENT.md's build command) and
# WhiteNoiseMiddleware, which serves straight out of this directory.
STATIC_ROOT = BASE_DIR / 'staticfiles'

# Django 4.2+ replaces STATICFILES_STORAGE with this dict — Django 6.0.7
# (this project's version) no longer recognizes the old setting name at
# all. Overriding only 'staticfiles'; 'default' (MEDIA_ROOT uploads) stays
# Django's own FileSystemStorage, unchanged — WhiteNoise never touches
# media, only static. CompressedManifestStaticFilesStorage gzips each file
# and content-hashes filenames (cache-busting `main.a1b2c3.js`-style names)
# — under DEBUG=True this app has no cache-busting at all today (see
# project_memory.md's Phase 8.98a stale-cache incident); this fixes that
# for every static asset once deployed, not just the one file that bit
# that phase.
STORAGES = {
    'default': {
        'BACKEND': 'django.core.files.storage.FileSystemStorage',
    },
    'staticfiles': {
        'BACKEND': 'whitenoise.storage.CompressedManifestStaticFilesStorage',
    },
}

# Media files (user uploads: Product.image, User.profile_image,
# SystemSettings.company_logo). BUG-10 (Phase 1) only installed Pillow to
# satisfy manage.py check's ImageField requirement — it never configured
# these, so nothing was actually servable until now (Phase 5). Dev-only
# serving is wired in config/urls.py, gated on DEBUG or
# SERVE_MEDIA_IN_PRODUCTION below.
MEDIA_URL = 'media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Phase 8.99 — RECOMMENDATION, decision deliberately left to the deployer
# rather than picked silently (see docs/project_memory.md Phase 8.99
# entry for the full writeup): this still writes to the local filesystem
# at MEDIA_ROOT. Render's default disk is ephemeral — every uploaded
# Product/Profile image is lost on the next deploy or restart unless a
# Render **persistent disk** is mounted at this exact path. Recommended
# path for this app's actual scale (small business inventory tool, not
# high-traffic): attach a Render persistent disk, then set
# SERVE_MEDIA_IN_PRODUCTION=True. For a larger/multi-instance deployment,
# external object storage (S3/Cloudinary via `django-storages`, not
# installed — would need a new dependency and real cloud credentials
# neither available nor verifiable in this phase) is the better long-term
# answer and the natural next step. Defaults to False so a fresh deploy
# with no disk attached fails LOUD (every image 404s) rather than
# silently "working" until the first redeploy wipes it — flip only once
# the disk is actually mounted.
SERVE_MEDIA_IN_PRODUCTION = os.environ.get('SERVE_MEDIA_IN_PRODUCTION', 'False') == 'True'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# Email (Phase 3.5 — frontend/notifications.py sends synchronously via
# send_mail(), no Celery yet). Console backend for local dev so nothing
# actually leaves the machine; override via .env once real SMTP exists.
EMAIL_BACKEND = os.environ.get('EMAIL_BACKEND', 'django.core.mail.backends.console.EmailBackend')
DEFAULT_FROM_EMAIL = os.environ.get('DEFAULT_FROM_EMAIL', 'noreply@stockwell.local')

# Phase 8.99 — ENVIRONMENT.md documents these 5 SMTP vars, but until now
# only EMAIL_BACKEND/DEFAULT_FROM_EMAIL were actually read anywhere in this
# file: setting EMAIL_BACKEND=...smtp.EmailBackend alone would have silently
# fallen back to Django's own SMTP defaults (localhost:25, no auth) rather
# than a real provider — a real, deploy-blocking gap for Phase 8.98e's
# emailed-credentials feature specifically, since that feature has no
# fallback delivery path at all if the email never sends (see
# project_memory.md's Phase 8.99 entry). Blank/insecure defaults here are
# intentional: this app must fail loud (a real connection error in the
# logs) rather than silently pretend to send mail it can't.
EMAIL_HOST = os.environ.get('EMAIL_HOST', '')
EMAIL_PORT = int(os.environ.get('EMAIL_PORT', '587'))
EMAIL_USE_TLS = os.environ.get('EMAIL_USE_TLS', 'True') == 'True'
EMAIL_HOST_USER = os.environ.get('EMAIL_HOST_USER', '')
EMAIL_HOST_PASSWORD = os.environ.get('EMAIL_HOST_PASSWORD', '')
# Phase 8.99f-7 — a hung Gmail/network connection would otherwise block
# the request indefinitely (Python's smtplib has no default timeout);
# this makes a stalled send fail fast, as a normal caught exception
# send_new_user_credentials_email()/_maybe_send_email() already handle,
# rather than hanging the whole request. 10s is generous for a real SMTP
# handshake+send; env-overridable for a slower link if ever needed.
EMAIL_TIMEOUT = int(os.environ.get('EMAIL_TIMEOUT', '10'))

# Phase 8.99f-7 — belt-and-suspenders on top of Django's own, already-
# reliable safety net: `manage.py test` calls
# django.test.utils.setup_test_environment(), which unconditionally
# overrides EMAIL_BACKEND to the locmem backend before any test runs,
# regardless of what .env says (confirmed live: running the full suite
# with a real Gmail app password sitting in EMAIL_HOST_PASSWORD sent
# zero real email — every test still used mail.outbox). This guard exists
# only so that mechanism is never the *only* thing standing between a
# populated EMAIL_HOST_PASSWORD and a real Gmail send during this
# project's own `manage.py test` invocation specifically — if the test
# subcommand is being run, pin locmem here too, before Django's own
# override even executes.
if len(sys.argv) > 1 and sys.argv[1] == 'test':
    EMAIL_BACKEND = 'django.core.mail.backends.locmem.EmailBackend'


# Production security headers (Phase 8.99 — SECURITY.md's "Production
# Security Settings" block). Tied to `not DEBUG`, the same established
# pattern SESSION_COOKIE_SECURE/CSRF_COOKIE_SECURE above already use
# (project_memory.md §13: no separate dev/production settings module
# exists, so this project conditions on DEBUG instead of importing a
# different file) — never True under local `runserver` (which serves
# plain HTTP; an SSL redirect there would just break every local request),
# always True once DEBUG=False is set for real in Render.
SECURE_SSL_REDIRECT = not DEBUG
SECURE_HSTS_SECONDS = 31536000 if not DEBUG else 0  # 1 year, matches SECURITY.md
SECURE_HSTS_INCLUDE_SUBDOMAINS = not DEBUG
SECURE_HSTS_PRELOAD = not DEBUG
# Render terminates TLS at its own edge/load balancer and forwards plain
# HTTP to this app — without telling Django which header marks a request
# as "was actually HTTPS at the edge," SECURE_SSL_REDIRECT above sees every
# forwarded request as insecure and redirects it again, forever (an
# infinite-redirect loop, not a cosmetic issue) — a well-known gotcha on
# every Heroku-style PaaS, not spec'd in SECURITY.md/DEPLOYMENT.md but
# required for SECURE_SSL_REDIRECT to actually work there. Render sets
# this header on every proxied request; safe to leave set under DEBUG too
# since it only takes effect when the header is actually present.
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
# Safe in both dev and prod — no HTTP-vs-HTTPS dependency, so not DEBUG-gated.
SECURE_CONTENT_TYPE_NOSNIFF = True
# Matches SECURITY.md; also Django's own default when XFrameOptionsMiddleware
# is installed (already was) — set explicitly per the doc rather than
# relying on the implicit default.
X_FRAME_OPTIONS = 'DENY'
# SECURITY.md also lists SECURE_BROWSER_XSS_FILTER — deliberately omitted:
# Django removed this setting in 4.0 (browsers themselves dropped the
# X-XSS-Protection header it controlled as ineffective/risky years ago).
# Setting it under Django 6.0.7 (this project's version) is simply inert,
# not a real control — disclosed here rather than added as dead cargo.
